version: '3'

services:
  sabnzbd:
    image: funkypenguin/sabnzbd:latest
    container_name: sabnzdb
    volumes:
      - "sabnzbd_data:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8080:8080
    env_file: uidgid.env
    environment:
      - EDGE=1
      - DOMAIN_NAME=sabnzbd.localhost
      - VIRTUAL_HOST=sabnzbd.localhost
      - LETSENCRYPT_HOST=sabnzbd.localhost
      - LETSENCRYPT_EMAIL=youremail@localhost
      - VIRTUAL_PORT=8080
    restart: always
    networks:
      - nginx_proxy-network

  couchpotato:
    image: linuxserver/couchpotato:latest
    container_name: couchpotato
    volumes:
      - "couch_data:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5050:5050
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=couchpotato.localhost
      - VIRTUAL_HOST=couchpotato.localhost
      - LETSENCRYPT_HOST=couchpotato.localhost
      - LETSENCRYPT_EMAIL=youremail@localhost
    restart: always
    networks:
      - nginx_proxy-network

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - "sonarr_data:/config"
    ports:
      - 8989:8989
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=sonarr.localhost
      - VIRTUAL_HOST=sonarr.localhost
      - LETSENCRYPT_HOST=sonarr.localhost
      - LETSENCRYPT_EMAIL=youremail@localhost
    networks:
      - nginx_proxy-network

networks: 
    nginx_proxy-network:
        external: true

volumes:
  sonarr_data:
  couch_data:
  sabnzbd_data:
