version: '3'

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - "/media/config/plex:/config"
      - "/media/tv:/data/tv"
      - "/media/movies:/data/movies"
      - "/media/transcode:/transcode"
    ports:
      - 32469:32469
      - 32400:32400
      - 32401:32401
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    env_file: uidgid.env
    environment:
      - VIRTUAL_HOST=plex.localhost
      - VIRTUAL_PORT=32400
      - VERSION=latest
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy-network
    restart: unless-stopped

  sabnzbd:
    image: funkypenguin/sabnzbd:latest
    container_name: sabnzdb
    volumes:
      - "/media/config:/config"
    ports:
      - 8080:8080
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=sabnzbd.localhost
      - VIRTUAL_HOST=sabnzbd.localhost
      - VIRTUAL_PORT=8080
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy-network
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - "/media/config/radarr:/config"
      - "/media/downloads:/downloads"
      - "/media/movies:/movies"
    ports:
      - 7878:7878
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=radarr.localhost
      - VIRTUAL_HOST=radarr.localhost
      - VIRTUAL_PORT=7878
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy-network
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - sabnzbd
      - plex
    volumes:
      - "/media/confic/sonarr:/config"
      - "/media/downloads:/downloads"
      - "/media/tv:/tv"
    ports:
      - 8989:8989
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=sonarr.localhost
      - VIRTUAL_HOST=sonarr.localhost      
      - VIRTUAL_PORT=8989
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy-network
    restart: unless-stopped

  nzbhydra:
    image: linuxserver/hydra
    container_name: nzbhydra
    volumes:
      - "/media/config/nzbhydra:/config"
      - "/media/downloads:/downloads"
    ports:
      - 5075:5075
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=nzbhydra.localhost
      - VIRTUAL_HOST=nzbhydra.localhost
      - VIRTUAL_PORT=5075
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy-network
    restart: unless-stopped

networks: 
    nginx_proxy-network:
        external: true