version: '3'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - "${configVolume}/plex:/config"
      - "${mediaVolume}/tv:/data/tv"
      - "${mediaVolume}/movies:/data/movies"
      - "${plexTranscode}:/transcode"
    network_mode: host
    environment:
      - VIRTUAL_HOST=plex.htpc
      - VIRTUAL_PORT=32400
      - VERSION=latest
      - NETWORK_ACCESS=internal
      - PLEX_CLAIM=claim-x9VGt9pFZGUmn9KqAysu
      - ADVERTISE_IP=http://192.168.10.195:32400/
      - HOTNAME=PlexServer
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - "${configVolume}/sabnzbd:/config"
      - '${downloadVolume}/complete:/downloads'
      - '${downloadVolume}/incomplete:/incomplete-downloads'
    ports:
      - 8080:8080
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=sabnzbd.htpc
      - VIRTUAL_HOST=sabnzbd.htpc
      - VIRTUAL_PORT=8080
      - NETWORK_ACCESS=internal
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy_network
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - "${configVolume}/radarr:/config"
      - "${downloadVolume}/complete:/downloads"
      - "${mediaVolume}/movies:/movies"
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=radarr.htpc
      - VIRTUAL_HOST=radarr.htpc
      - VIRTUAL_PORT=7878
      - NETWORK_ACCESS=internal
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy_network
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - sabnzbd
      - plex
    volumes:
      - "${configVolume}/sonarr:/config"
      - "${downloadVolume}/complete:/downloads"
      - "${mediaVolume}/tv:/tv"
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=sonarr.htpc
      - VIRTUAL_HOST=sonarr.htpc      
      - VIRTUAL_PORT=8989
      - NETWORK_ACCESS=internal
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy_network
    restart: unless-stopped

  nzbhydra:
    image: linuxserver/hydra
    container_name: nzbhydra
    volumes:
      - "${configVolume}/nzbhydra:/config"
      - "${downloadVolume}:/downloads"
    env_file: uidgid.env
    environment:
      - DOMAIN_NAME=nzbhydra.htpc
      - VIRTUAL_HOST=nzbhydra.htpc
      - VIRTUAL_PORT=5075
      - NETWORK_ACCESS=internal
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - nginx_proxy_network
    restart: unless-stopped

networks: 
    nginx_proxy_network:
        external: true
