version: '3'

services:
    pihole:
        image: diginc/pi-hole:latest
        container_name: pihole
        dns:
            - 127.0.0.1
            - 1.1.1.1
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "443:443/tcp"
        volumes:
            - '/var/log/pihole.log:/var/log/pihole.log'
        networks:
            - web
        cap_add:
            - NET_ADMIN
        environment:
            ServerIP: ${serverip}
            PROXY_LOCATION: pihole
            VIRTUAL_HOST: pihole.${domainName}
            VIRTUAL_PORT: 80
        extra_hosts:
            # LAN hostnames for other docker containers using reverse proxy
            - 'plex plex.${domainName}:${serverip}'
            - 'radarr radarr.${domainName}:${serverip}'
            - 'sonarr sonarr.${domainName}:${serverip}'
            - 'sabnzbd sabnzbd.${domainName}:${serverip}'
        restart: always
networks:
    web:
      external:
        name: traefik_webgateway
