version: '3'

services:
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        dns:
            - 127.0.0.1
            - 1.1.1.1
        ports:
            - "0.0.0.0:53:53/tcp"
            - "0.0.0.0:53:53/udp"
            - "0.0.0.0:67:67/udp"
            - "0.0.0.0:8053:80/tcp"
            - "0.0.0.0:4043:443/tcp"
        labels:
            - "traefik.backend=pihole"
            - "traefik.frontend.rule=Host:pihole.${domainName}"
        volumes:
            - '/var/log/pihole.log:/var/log/pihole.log'
        networks:
            - web
        cap_add:
            - NET_ADMIN
        environment:
            ServerIP: ${serverip}
            PROXY_LOCATION: pihole
            VIRTUAL_HOST: pihole.${domainName}
            VIRTUAL_PORT: 80
        extra_hosts:
            # LAN hostnames for other docker containers using reverse proxy
            - 'plex plex.${domainName}:${serverip}'
            - 'radarr radarr.${domainName}:${serverip}'
            - 'sonarr sonarr.${domainName}:${serverip}'
            - 'sabnzbd sabnzbd.${domainName}:${serverip}'
        restart: always
networks:
    web:
      external:
        name: traefik_webgateway
