version: '3'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - "${CONFIG_VOLUME}/plex:/config"
      - "${MEDIA_VOLUME}/video/TV:/data/tvshows"
      - "${MEDIA_VOLUME}/video/Movies:/data/movies"
      - "${MEDIA_VOLUME}/video:/data/video"
      - "${MEDIA_VOLUME}/audio:/data/audio"
    network_mode: host
    environment:
      ADVERTISE_IP: http://${SERVERIP}:32400/
      PLEX_UID: ${UID}
      PLEX_GUID: ${GUID}      
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:plex.${DOMAINNAME}"
      - "traefik.port=32400"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - "${CONFIG_VOLUME}/jellyfin:/config"
      - "${MEDIA_VOLUME}/video:/media"
    ports:
      - ${JELLYFIN_PORT}:8096
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jellyfin"
      - "traefik.frontend.rule=Host:jellyfin.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped


  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - "${CONFIG_VOLUME}/sabnzbd:/config"
      - "${DOWNLOAD_VOLUME}/complete:/downloads"
      - "${MEDIA_VOLUME}:/media"
    ports:
      - ${SABNZBD_PORT}:8080
      - 9090:9090
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sabnzbd"
      - "traefik.frontend.rule=Host:sabnzbd.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - sabnzbd
      - hydra    
    volumes:
      - "${CONFIG_VOLUME}/radarr:/config"
      - "${DOWNLOAD_VOLUME}/complete:/downloads"
      - "${MEDIA_VOLUME}/video/Movies:/media/movies"
    ports:
      - 7878:7878
      - ${RADARR_PORT}:${RADARR_PORT}
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:radarr.${DOMAINNAME}"      
      - "traefik.port=7878"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  sonarr:
    image: lsiodev/sonarr-preview
    container_name: sonarr
    depends_on:
      - sabnzbd
      - hydra
    volumes:
      - "${CONFIG_VOLUME}/sonarr-preview:/config"
      - "${DOWNLOAD_VOLUME}/complete:/downloads"
      - "${MEDIA_VOLUME}/video/TV:/media/tv"
    ports:
      - 8989:8989
      - ${SONARR_PORT}:${SONARR_PORT}
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
      VERSION: preview
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:sonarr.${DOMAINNAME}"
      - "traefik.port=8989"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    depends_on:
      - sabnzbd
      - hydra
    volumes:
      - "${CONFIG_VOLUME}/lidarr:/config"
      - "${DOWNLOAD_VOLUME}/complete:/downloads"
      - "${MEDIA_VOLUME}/audio:/media/audio"
    ports:
      - 8686:8686
      - ${LIDARR_PORT}:${LIDARR_PORT}      
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lidarr"
      - "traefik.frontend.rule=Host:lidarr.${DOMAINNAME}"
      - "traefik.port=8989"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    depends_on:
      - sabnzbd
      - hydra    
    volumes: 
      - "${CONFIG_VOLUME}/lazylibrarian/config:/config"
      - "${DOWNLOAD_VOLUME}/complete:/downloads"
      - "${MEDIA_VOLUME}/books:/books"
    ports:
      - 5299:5299
      - ${LAZYLIBRARIAN_PORT}:${LAZYLIBRARIAN_PORT}          
    environment: 
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lazylibrarian"
      - "traefik.frontend.rule=Host:librarian.${DOMAINNAME}"
      - "traefik.port=5299"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  hydra:
    image: linuxserver/hydra
    container_name: hydra
    volumes:
      - "${CONFIG_VOLUME}/hydra:/config"
      - "${DOWNLOAD_VOLUME}:/downloads"
    ports:
      - 5075:5075
      - ${HYDRA_PORT}:${HYDRA_PORT}            
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hydra"
      - "traefik.frontend.rule=Host:hydra.${DOMAINNAME}"
      - "traefik.port=5075"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped
  
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    depends_on:
      - plex    
    volumes: 
      - ${CONFIG_VOLUME}/tautulli:/config
      - ${CONFIG_VOLUME}/tautulli/logs:/logs:ro
    ports:
      - 8181:8181
      - ${TAUTULLI_PORT}:${TAUTULLI_PORT}      
    environment: 
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=tautulli"
      - "traefik.frontend.rule=Host:tautulli.${DOMAINNAME}"
      - "traefik.port=8181"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped


    tdarr:
      image: haveagitgat/tdarr
      container_name: tdarr
      ports:
              - 8265:8265
      environment:
              - TZ=${TZ}
              - PUID=${UID}
              - PGID=${GUID}
      volumes:
              - /media/drive/Movies:/home/Tdarr/Media/Movies
              - ${CONFIG_VOLUME}/tdarr:/home/Tdarr/Documents/Tdarr
              - ${CONFIG_VOLUME}/tdarr/TdarrDB:/var/lib/mongodb

networks:
     traefik_proxy:
      external: true
