version: '3'

services:
    nginx:
        image: 'jwilder/nginx-proxy:latest'
        container_name: nginx-proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - '../data/nginx/vhost.d:/etc/nginx/vhost.d:ro' # to update vhost configuration
            - '../data/nginx/html:/usr/share/nginx/html' # to write challenge files
            - '../data/nginx/certs:/etc/nginx/certs:ro' # this should match the ssl-companion container
           # - './network_internal.conf:/etc/nginx/network_internal.conf'
        networks:
            - proxy-network
        restart: unless-stopped
networks: 
    proxy-network:
        driver: bridge