version: '3'

services:
    nginx:
        image: 'jwilder/nginx-proxy:latest'
        container_name: nginx-proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - '../data/nginx/vhost.d:/etc/nginx/vhost.d:ro' # to update vhost configuration
            - '../data/nginx/html:/usr/share/nginx/html' # to write challenge files
            - '../data/nginx/certs:/etc/nginx/certs:ro' # this should match the ssl-companion container
           # - './network_internal.conf:/etc/nginx/network_internal.conf'
        networks:
            - proxy_network
        restart: unless-stopped
    pihole:
        image: diginc/pi-hole:latest
        container_name: pihole
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '8053:80/tcp'
        volumes:
            - '../data/pihole/:/etc/pihole'
            - '/var/log/pihole.log:/var/log/pihole.log'
        #network_mode: host
        networks:
            - proxy_network
        cap_add:
            - NET_ADMIN
        environment:
            ServerIP: 192.168.10.195
            PROXY_LOCATION: pihole
            VIRTUAL_HOST: pihole.htpc
            VIRTUAL_PORT: 80
        extra_hosts:
            # LAN hostnames for other docker containers using jwilder
            - 'plex plex.htpc:192.168.10.195'
            - 'radarr radarr.htpc:192.168.10.195'
            - 'sonarr sonarr.htpc:192.168.10.195'
            - 'sabnzbd sabnzbd.htpc:192.168.10.195'
        restart: always
networks:
    proxy_network:
